// Backend error codes for consistent error handling
// across the application
export const BACKEND_ERROR_CODES = {
    INVALID_ROUTE: 'INVALID_ROUTE',
    INVALID_APP_ID: 'INVALID_APP_ID',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_USERNAME: 'INVALID_USERNAME',
    EMAIL_CONFIRMATION_EXPIRED: 'EMAIL_CONFIRMATION_EXPIRED',
    MAGICLINK_EXPIRED: 'MAGICLINK_EXPIRED',
    PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED',
    INVALID_REQUEST_TOKEN: 'INVALID_REQUEST_TOKEN',
    BLOK_NOT_FOUND: 'BLOK_NOT_FOUND',
    INVALID_BLOK_NAME: 'INVALID_BLOK_NAME',
    INVALID_BLOK_ID: 'INVALID_BLOK_ID',
    INVALID_BLOK_DATA: 'INVALID_BLOK_DATA',
    INVALID_QUERY_FILTER: 'INVALID_QUERY_FILTER',
    INVALID_QUERY_LIMIT: 'INVALID_QUERY_LIMIT',
    INVALID_AUTHENTICATION_METHOD: 'INVALID_AUTHENTICATION_METHOD',
    INVALID_UPDATE_DATA: 'INVALID_UPDATE_DATA',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    INVALID_API_KEY: 'INVALID_API_KEY',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    
    // no error reporting functions for error codes below
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    EMAIL_SEND_FAILURE: 'EMAIL_SEND_FAILURE',
}